getredash/website

- onpremise/setup/settings-environment-variables.md
Hi !
I found that default value of `REDASH_ALLOW_SCRIPTS_IN_USER_INPUT` is `false`.
See https://github.com/getredash/redash/blob/master/redash/settings.py#L218 .
Thanks 😄
> Fixed default value of REDASH_ALLOW_SCRIPTS_IN_USER_INPUT to "false"

- user-guide/query-examples-hacks/sunburst-sankey-example.md
Due to the filename typo the URL for https://redash.io/help/query-examples-hacks/sunbusrt-sankey-example.html would change as well, so I'm not sure of the implications of that, such as needing to set up a redirect.
> Correct "sunbusrt" typo in filename and header

- user-guide/query-examples-hacks/redash-hacks.md
> Fix typo in clickable URL hack example

- onpremise/setup/supported-data-sources-options-reqs.md
- user-guide/SUMMARY.md
- user-guide/aboutrd/aboutrd.md
- user-guide/queries/querying_elasticsearch.md
- user-guide/queries/writing_queries.md
- website/_data_sources/elasticsearch.html
- website/_layouts/default.html
Hi, `Elasticsearch` is the correct spelling, NOT `ElasticSearch` and `Elastic Search`.
- https://www.elastic.co/products/elasticsearch
So, I renamed to `Elasticsearch`.
( Please review together -> https://github.com/getredash/redash/pull/2222 :octocat:  )
- https://redash.io/help-onpremise/setup/supported-data-sources-options-reqs.html
- http://help.redash.io/article/111-querying-elastic-search
- http://help.redash.io/article/119-supported-data-sources
- And more ❓ 
Please review, thank you 👍
> Renamed to "Elasticsearch"

- onpremise/dev/docker.md
I found a mistake of usage of docker-compose.
`docker-compose rebuild` doesn't exist. (`docker-compose build` is right.)
https://docs.docker.com/compose/reference/build/
> Modify docker-compose usage

- website/_kb/data-sources/querying-a-google-spreadsheet.md
This might just have been me, but I spend several hours wondering why `SELECT * FROM 1DFuuOMFzNoFQ5EJ2JE2zB79-0uR5zVKvc0EikmvnDgk` wasn't working. I'd like to prevent other people from doing the same.
> Clarify Spreadsheet query text

- website/_kb/open-source/dev-guide/docker.md
The documentation links to the redash repo via SSH which requires authentication.  I've changed it to use the https link so people without a a github account can reference it.
> Update docker.md with https based clone url

- website/_kb/data-sources/supported-data-sources.md
Can we confirm whether ScyllaDB is still supported? I don't see a query runner for it in the main repo.
Connected to #129.
> Added data sources with query runners not shown in the docs already

- src/components/Header.jsx
Fixes #185. Simply moved the click to the clickable portion. Works fine.
Also, made the link open in a new window since it's external.
> Fix: Top menu link to the forum doesn't work

- src/pages/kb/data-sources/querying-mongodb.md
Links cannot include newline characters.
> Link to MongoDB documentation is broken

- src/templates/HelpArticle.jsx
Allows communicating with parent window to determine "drawer" mode.
* Ignored if not in an iframe
* Once state set, it's stored in session storage to avoid need for further communication.
Would be able to test this with corresponding redash app PR.
> Dynamic setting “drawer” mode

- src/templates/HelpArticle.jsx
Before | After
------------ | -------------
The biggest difference in in mobile/drawer mode.
> Remove current page title from breadcrumbs

- src/components/hoc/withIframeHook.jsx
- src/pages/help/index.jsx
- src/templates/HelpArticle.jsx
Follow up on https://github.com/getredash/website/pull/200#issuecomment-463638668.
Reverted previous postMessage communication.
Instead determining "drawer" mode by detecting if loaded in iframe.
Since the classname is added directly on `componentDidMount` there is no flicker visible at all.
Now the parent window simply loads the page in iframe without any trickery.
> Simplified drawer method

- src/scss/_components/_page-about.scss
- src/scss/_components/_section.scss
> Contributor card layout fixes

- gatsby-browser.js
Help doc links rely on url anchoring but reportedly sometimes it doesn't work.
Most likely, the code in `gatsby-browser.js` is the cause.
```js
if (
typeof window !== 'undefined' &&
(!location.action || location.action === 'push')
) {
setTimeout(() => {
window.scrollTo(0, 0)
})
}
```
My guess is that the above code is meant to make sure navigation to pages will scroll to top (single page app requirement) unless navigated "back" (hence the location.action check).
BUT, from what I understand, Gatsby deals with this on it's own with [gatsby-react-router-scroll](https://www.npmjs.com/package/gatsby-react-router-scroll) and I also tested this PR and found no prob.
> Removed legacy scrollTo code

- src/pages/kb/open-source/dev-guide.md
- src/pages/kb/open-source/dev-guide/end-to-end-tests.md
I postponed too much this one :sweat_smile:. This creates a page for E2E Tests documentation with instructions to Run Cypress locally.
I also want to add an "Our Practices" section further (probably in this page). I should do it after some discussion about it. This way we'll have documented our practices for: naming conventions, when to/not to write e2e tests, things to avoid when coding, etc.
Ideas for improvements are, as always, accepted :grin:
> Add E2E Tests doc page

- src/components/Header.jsx
Fixes https://github.com/getredash/website/issues/221
Swapped the `<Link>` for a `<a>`. No sweat 😎
> Fixed Help dropdown clickable area

- src/scss/_components/_forms.scss
Fixes #230.
Because of the h3 padding hack (for proper auto-scrolled positioning) the bottom section overlaps the searchbar and obscures its clickable area.
There are many ways to approach this. I went for the safest (in terms of causing new problems).
Verified on Linux Chrome.
> Searchbox click - fix issue #230

- src/scss/_components/_kb.scss
Fixes #210
This spacing is supposed to affect only Knowledge Base titles (so that anchors would be spaced correctly under the fixed header).
Before:
After:
> Fixed h3 spacing issue #210

- src/scss/_components/_kb.scss
Noticed that multi line title looks bad. Fixed it.
Before | After
------------ | -------------
------------------
But one line remains unchanged
> Fixed title line height

- src/pages/kb/user-guide/alerts/setting-up-an-alert.md
- src/pages/kb/user-guide/dashboards/dashboard-editing.md
Fixed broken link to the scheduled queries page (extra space breaks the `{% _link %}` behavior. Added stress that Alerts should be configured with scheduled queries.
> Scheduled query changes

- gatsby-config.js
- src/pages/index.jsx
- src/pages/kb/open-source/dev-guide.md
I couldn't reproduce this, but based on some research it seems that others who had similar issue to ours resolved it by removing the gatsby-plugin-offline plugin. As offline support is not a priority for our website/knowledge base, I removed it.
I'm keeping #244 open until we can see it doesn't occur again.
> Remove gatsby-plugin-offline

- gatsby-browser.js
- package-lock.json
- package.json
- src/components/Layout.jsx
Discussion here https://discuss.redash.io/t/should-the-help-drawer-retain-state/3832/8.
Works with https://github.com/getredash/redash/pull/3890.
Sends a postMessage with changed url to parent so it updates the "open in new window" button in the help drawer.
This PR diff looks big but it actually just turns a functional component into a class component and adds mount/unmount methods.
> Report url change to parent

- src/pages/kb/data-sources/bigquery-setup.md
Fixes #251. Adds details about setup fields including the [Scanned Data Limit](https://github.com/getredash/redash/pull/710) that was added in 2015. I also copied over the Service Account setup details from #142 as well.
> Updates to BigQuery setup documentation

- src/pages/kb/user-guide/querying/query-filters.md
- src/pages/kb/user-guide/querying/query-parameters.md
Fixed #255 
Found 2 instances in which the `{% link url %}` had an extra space.
> Fixed broken internal links

- README.md
This is useful when the process is run in a VM, rather than on the local computer.
> Add information to the README for running Gatsby on non-localhost address

- src/pages/kb/open-source/dev-guide/docker.md
It was a bit disconcerting the first time going through this, having the command take over the terminal session and the instructions not being clear that this was intended.
This PR adjusts things so the startup is backgrounded instead, allowing the user to continue with the instructions.
An alternative approach, would be to mention after the `docker-compose up` that the user should leave that command running then open a new terminal window to continue on.  Happy to update this PR to use that approach instead, if it's preferred.
> Minor tweaks so new dev setup works with a single terminal session

- src/pages/community/index.jsx
Noticed a trivial typo in a variable name, so fixed that while updating our main repo forks count. :smile:
> Fix a trivial internal typo, and update the GitHub repo fork count

- _redirects
- src/pages/kb/data-sources/querying-urls.md
- src/pages/kb/data-sources/supported-data-sources.md
This PR:
* Moves the JSON info above the URL info
* Adds a link to this doc from the "Supported Data Sources" list
* Moves the JSON/URL info under Data Source → Setup, which seems like the more logical place people would go looking for it, even though much of it is to do with Querying
* Adds a redirect from the old website location to the new location
> Make JSON data source info easier to find

- src/pages/kb/data-sources/querying-urls.md
I wanted to remove the callout about the JSON data source being available only in SaaS, but then stumbled at other things that required changing.
> Update JSON data source documentation

- src/pages/kb/open-source/admin-guide/how-to-upgrade.md
Advises users to install one semantic version at a time. Specifically warns against upgrading to V8 from versions earlier than V7.
> V8 upgrade warning

- src/pages/kb/user-guide/alerts/setting-up-an-alert.md
Enough people miss this it makes sense to put it in a `callout` for higher visibility.
See the third callout in orange.
> Moves "alerts don't work with parameters" verbiage

- src/pages/kb/data-sources/bigquery.md
While investigating https://github.com/getredash/website/issues/393 I saw that this page and [this one](https://redash.io/help/user-guide/querying/writing-queries) disagree about the token limit for Auto Complete. This PR makes the BQ doc match the `writing-queries` page.
> Updates BQ doc to reflect the 5000 token schema limit

- src/pages/kb/user-guide/integrations-and-api/api.md
Fixing problems with: ebe13531147d6e9aaa4ac93c31f10b03b5200d30
- API is not "internal". It's just the API.
- Endpoints should be preceded by a forward slash `/`
- No need to document the `/refresh` API as it's slated for removal.
- The `/api/results` endpoint can return a cached result sometimes.
- `/api/dashboards/<dashboard_id>` only works for POST and DELETE
- `/api/dashboards/<dashboard_slug>` is required for a GET
Closes https://github.com/getredash/website/issues/373
> Updates to API documentation

- src/pages/kb/data-sources/jira.md
After some debugging with a customer this evening we determined that the username for Jira is the user email address. The API doesn't raise authentication errors, though, so this wasn't obvious.
[Relevant JIRA API Doc](https://developer.atlassian.com/server/jira/platform/basic-authentication/):
> ## No authentication challenge
>
> Because Jira permits a default level of access to anonymous users, it does not supply a typical authentication challenge. 
Adding a reference to this to help future users.
Closes #406
> Update Jira doc username definition

- src/pages/kb/user-guide/querying/query-parameters.md
On June 20th, 2020 we updated the Query Parameters youtube video. We also removed the previous version. This PR updates the embed code to point at the new video since the old one is no longer available.
Closes #439
> Query Parameters doc page: update youtube embed

- src/pages/kb/user-guide/visualizations/table-visualizations.md
Details the "Allow HTML Content" toggle in the table viz editor and gives an example use-case.
Closes https://github.com/getredash/website/issues/140
> Document HTML escape behavior in tables

- src/pages/kb/faq/hosted-redash_category.md
- src/pages/kb/user-guide/integrations-and-api/ssh-tunnel-api.md
- ssh-tunnels.md
Explains how to configure SSH tunnels on SaaS Redash using the `options.ssh_tunnel` configuration key. The new page appears in the User Guide under _Integrations & API_. And is linked from the _Hosted Redash FAQ_.
> Add SaaS SSH Tunnel API documentation

- src/pages/kb/user-guide/integrations-and-api/api.md
Deleting a dashboard with the API wants the slug (not the dashboard id)
> Deleting a dashboard with the API requires the slug (not the dashboard id)

- src/pages/kb/user-guide/integrations-and-api/api.md
This was brought up on the forum here: https://discuss.redash.io/t/executing-query-without-max-age-key/7062/4
> Revises /results documentation to better reflect behavior.

- src/pages/kb/open-source/dev-guide/end-to-end-tests.md
Update Cypress docs with some of the changes we had recently:
- Cypress is now a dev dependency, so no need to `npm run cypress:install`
- `db-seed` command was incorporated in `npm run cypress start`
- `start` command no longer builds, so `npm run cypress build` was added
For review check https://github.com/getredash/website/pull/512/commits/0fbec657d81c2a42a0cb2cb74c7ada6d84a5c332
> Update Cypress docs

- src/pages/kb/user-guide/integrations-and-api/creating-a-zap.md
A customer on app.redash.io rightfully pointed out that the former instructions don't work anymore. When I click to view my profile the URL now says `https://app.redash.io/<org slug>/users/me`. I believe the only mechanism for viewing a user ID within the interface is from the **Users** tab of settings. This PR updates the documentation to reflect this.
> Revise zapier instructions: where to find user id

- src/pages/kb/user-guide/integrations-and-api/api.md
Adds info about behavior of GET requests to the `/results` endpoint.
Fixes https://github.com/getredash/website/issues/434
> Document error "No cached result found for this query"

- src/pages/case-studies/bubbleiq/index.jsx
A customer on app.redash.io reported that the BubbleIQ case study has a dead link to their website. It looks like BubbleIQ folded. This PR maintains the case study but removes the link to their website.
> Fix: BubbleIQ's website is no longer active resulting in a dead link.

- src/pages/kb/data-sources/databricks.md
There has been some confusion among Databricks users exactly what to type when setting up the Databricks data source. This PR adds clarifying verbiage.
> Clarify Databricks schemas

- src/pages/kb/open-source/admin-guide/env-vars-settings.md
- src/pages/kb/open-source/dev-guide/docker.md
- src/pages/kb/user-guide/users/authentication-options.md
This PR updates the docker development setup steps now that [#5655](https://github.com/getredash/redash/pull/5655) has merged. Also it clarifies the behaviour of "Allowed Domains" in the Google Login settings.
> Clarifying dev setup and Google Login

- src/data/footer_links.yml
This patch removes deprecated 'Blog' link from the global footer navigation.
This PR is related to discussion https://github.com/getredash/redash/discussions/6849.
- GitHub Codespaces
- Build and Deploy with Docker (As described in your [README.md](https://github.com/getredash/website#docker-setup))
> Remove 'Blog' from the global footer nav

- src/pages/kb/user-guide/integrations-and-api/api.md
- This PR fixes an invalid sample JSON message in `POST /api/queries/<id>/results` documentation.
> Fix an invalid sample JSON message in api.md

- src/pages/kb/open-source/admin-guide/how-to-upgrade.md
- src/pages/kb/open-source/admin-guide/secrets.md
- src/pages/kb/open-source/setup.md
Fix https://github.com/getredash/setup/issues/66
Resolves an issue where the 'docker-compose.yml' filename was changed to `compose.yaml`
in the `redash`, `setup` repo, but the documentation was not changed.
> Responding to 'docker compose' filename changes

- src/pages/kb/open-source/setup.md
Fix https://github.com/getredash/setup/issues/67
Reference: https://github.com/getredash/redash/discussions/6812
Since Redash has been removed from the 'Digital Ocean Marketplace', remove its entry from the article.
> Remove 'Digital Ocean' section

- .restyled.yaml
This PR reconfigures Restyled, which was currently used as a linter.
For consistency with the original repo, I have referenced the configruation files from the original repo: https://github.com/getredash/redash/blob/master/.restyled.yaml
Feel free to leave any comments or reviews. Thank you.
> Reconfigure Restyled

- gatsby-config.js
Fix #710 
Add Content-Security-Policy header to allow all frame ancestors. and 'X-Frame-Options' retains 'DENY'.
Options other than 'DENY' are unavailable because there is only 'SAMEORIGIN'. 'ALLOW-FROM origin' option is obsolete.
You can test this PR by following link: https://dapper-tapioca-6fa259.netlify.app/
Any comments or review are welcome. Thank you.
> Related: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
> Add Content-Security-Policy header to allow all frame ancestors

- src/pages/kb/open-source/admin-guide/https-ssl-setup.md
This is a follow up PR from #641, improving the cipher list and related settings.
The updated settings are from the [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org).
> Use HTTPS settings from the Mozilla SSL Config Generator

- .github/workflows/restyled.yml
It looks like Restyled, which we're using as a linter, recently migrated to GitHub Actions from GitHub Apps.
So with this PR, we are also migrate to GitHub Actions. Related: https://docs.restyled.io/news/github-actions-pivot/
This change has also been tested in fork.
Commit that add this workflow (actual change to current PR): https://github.com/lucydodo/website/commit/191b27d17661a68349dc0bfe5801683beaccf83f
Induction PR: https://github.com/lucydodo/website/pull/1
Generated PR: https://github.com/lucydodo/website/pull/2
Any comments or review are welcome. Thank you.
> Migrate Restyled to GitHub Actions
