onpremise/SUMMARY.md, onpremise/misc/dash-filters-flags.md, user-guide/alerts/how-to-setup-an-alert.md, user-guide/queries/query_actions.md
and added that it works well from 0.11
=> dashboard filters/flags added to on-premise

onpremise/setup/supported-data-sources-options-reqs.md, user-guide/SUMMARY.md, user-guide/queries/query-google-spreadsheets.md
Added /help article
Refined /on-prem article and remove the api key note
=> Google Spreadsheets

user-guide/queries/query-google-spreadsheets.md, website/_layouts/default.html, website/index.html
1. I phrased things a bit differently - both in meta aread and in the
actual main page
2. Also - removed the last 2 "features" from the list of 8 (and
rearranged it to be 3 in a row).
3. Changed the Demo button to be "See plans" link
Not all was discussed and asked for so feel free to comment or decline
:)
=> Metadata and text changes

user-guide/getting_started/getting_started.md
Looks like someone switched []() to ()[]. #latenightcodingproblems
=> Broken Link fixed

user-guide/dashboards/dashboards.md
I started by correcting "column" to "colon", then changed other parts of the doc to improve readability (IMO).
=> Misc changes to grouping dashboards docs

user-guide/queries/writing_queries.md
Documentation for: https://github.com/getredash/redash/pull/1504
This is just a start, interested to see what you want here.
=> Update Queries docs to talk about global parameters

user-guide/SUMMARY.md
I was trying to acces the sunburst/sankey example but the link was broken. Hope this fixes it.
=>  Fixed typo and link to sunburst-sankey-example.md

user-guide/query-examples-hacks/redash-hacks.md
I fixed typo of docs "Redash Hacks" !
Thanks 👍
=> Fixed typo of docs "Redash Hacks"

onpremise/setup/ldap-authentication.md
Documentation for https://github.com/getredash/redash/pull/1836
=> Add LDAP documentation 

onpremise/setup/ldap-authentication.md
Depends on https://github.com/getredash/redash/pull/2184
=> Rename REDASH_SEARCH_DN to REDASH_LDAP_SEARCH_DN

website/_kb/user-guide/querying/query-filters.md
This was making the query fail
=> remove space in COUNT (0)

website/_kb/data-sources/supported-data-sources.md
URL:
https://redash.io/help/data-sources/supported-data-sources
=> Add CockroachDB and MapD

website/_kb/open-source/admin-guide/env-vars-settings.md
Add new settings and delete settings that are not used in current release version.
URL:
https://redash.io/help/open-source/admin-guide/env-vars-settings
=> Update environment variables settings

website/_assets/stylesheets/_components/_page-price.scss, website/_assets/stylesheets/_components/_popover.scss, website/_assets/stylesheets/main.scss, website/pricing.html
=> Pricing page update with new plans and design

website/_kb/data-sources/supported-data-sources.md
=> Link instructions to supported data sources where we can + add CSV as a data source

website/_kb/open-source/dev-guide/setup.md
`../setup/settings-environment-variables.md` broken link. Please check.
=> Fix broken link

website/_kb/user-guide/users/authentication-options.md
Based on my trial & error experience whilst integrating with Okta, I have modified steps which otherwise I had to figure out by reading code & debugging both ends.
=> Updating SAML steps

website/_kb/open-source/setup.md
docker up is not a command.  docker-compose up is
=> fix docker command to restart server

website/_kb/data-sources/querying-a-google-spreadsheet.md
Updated links to Google resources. Tightened grammar. Fixed formatting for some links that overflowed oddly on mobile devices.
Ref getredash/redash#3160.
=> Revised Google Sheets data source connection instructions.

website/index.html
We don't really bother updating it. Until we make it dynamic and actually show a real number, it's not authentic to show an outdated count.
=> Remove the signups count

website/_kb/user-guide/dashboards/dashboard-editing.md
There were a couple places where the same information was written twice. I combined those and added info about using Markdown in dashboard text boxes.
=> Cleaned up grammar. Added info about using Markdown in text boxes

website/_kb/user-guide/users/profile-pictures.md
* Title capitalization change (A -> a) (I'm usually using http://titlecapitalization.com/# as reference).
* Remove callout about clearing browser cache, I think it just makes it confusing, specially when we already mention they should wait 5 minutes.
* Clarify about caching.
=> Update profile pictures page

website/_assets/stylesheets/_components/_kb.scss, website/_assets/stylesheets/_components/_section.scss
=> Fix scrolling position of KB headers

bin/build
=> Run Aloglia index only on production builds

src/components/Layout.jsx, src/scss/_components/_globals.scss, src/scss/_components/_typography.scss
=> Always stick footer to the bottom

src/pages/text_pages/privacy.md
=> Fix: policy page lead paragraph didn't have the class applied

src/components/ArticlesList.jsx, src/pages/help/index.jsx
=> Fix: sort articles in KB by order if available

src/pages/kb/user-guide/querying/query-results-data-source.md
=> Updates to the query results data source page.

src/components/ContributorCard.jsx
Didn't test this myself, just updated the code through github. (I'll figure out how to run the website locally if needed :slightly_smiling_face:, but I guess netlify will do it)
=> Fix twitter link in ContributorCard

src/components/SectionGetStarted.jsx
=> Fixed typo

src/pages/slack_failure/index.jsx, src/pages/slack_success/index.jsx
=> Slack auth failure/success pages

src/pages/kb/user-guide/visualizations/cohort-howto.md, src/pages/kb/user-guide/visualizations/visualization-types.md
Straightforward content update.
=> Added details about cohort visualization

src/pages/kb/open-source/dev-guide/end-to-end-tests.md
Made some changes to structure and wording.
=> Ranbena suggested changes

src/pages/contact/index.jsx
=> Fix contact form

src/pages/kb/user-guide/users/authentication-options.md
=> Added specific okta setup instructions.

src/pages/kb/user-guide/querying/query-parameters.md
=> Clarify query parameter safety and embed rules

src/pages/kb/data-sources/querying-mongodb.md
=> Updates to the MongoDB query page.

src/pages/help/index.jsx
This PR is to handle two small things that popped to me when I used the [Help Search](https://redash.io/help/):
- The Form Submits when you press Enter and you lose what you were typing (just added a `preventDefault`);
- Sometimes the showed result is actually a **previous** one and not the **current** - Now making sure the state is set before trigger the search.
=> Fix form submission and make sure state is set before search

src/pages/kb/user-guide/dashboards/dashboard-editing.md
+ Tightened grammar for this section
+ Added info about the refresh query string variable
=> Fixes #285

src/pages/kb/open-source/dev-guide/docker.md
I hit [this error](https://discuss.redash.io/t/installation-projet-erreur-with-docker-compose-up/3268) as well. Docker's default was 2GB and this error is otherwise _very_ hard to diagnose and then debug.
=> Update docker dev instructions

src/pages/kb/open-source/admin-guide/usage-data.md
Help doc for getredash/redash#4108.
=> Information about usage data sharing

src/pages/about/index.jsx
=> :wave: goodbye, Justin.

src/config/algolia.js
=> Use article's text for Algolia indexing

_redirects, src/pages/kb/open-source/setup.md, src/pages/kb/user-guide/querying/query-parameters.md
* Adds redirect for old Okta instructions
* Adds clarity to the setup guide
* Combines the date and date-time parameter paragraphs in query-parameters.md
* Adds clarity about scheduling and quick date ranges in query-parameters.md
=> Routine updates to the documentation.

src/pages/kb/open-source/dev-guide/setup.md
=> Update dev guide to reference Python 3, RQ and more

_redirects
From https://community.netlify.com/t/changed-behavior-in-redirects/10084
Netlify is changing their redirect behavior. In our case, forced redirects are always preferred.
Their change takes effect on April 7th.
=> Adds redirect force rules

src/pages/kb/open-source/dev-guide/docker.md
I encountered `errno 134` and not `errno 137` while running it for the first time.
Thought it would be good to add.
=> Update docker.md to catch other error code

src/pages/kb/user-guide/users/authentication-options.md
=> Added instructions on how to configure the Auth0 to the docs

src/pages/kb/data-sources/amazon-athena.md
Taken straight from feedback from @arikr. I'm a bit out of my element whether this is accurate or the right way to put it.
=> Additional athena documentation.

src/pages/kb/data-sources/csv-files.md
Dropbox changed the way their direct download links behave. This doc mirrors that change.
=> CSV Data Source: Revise dropbox instructions

src/pages/pricing/index.jsx
Fixes missing space between "please" and "contact".
=> Pricing page typo fix

src/pages/kb/user-guide/integrations-and-api/ssh-tunnel-api.md
Clarifies location to save Redash's public key for app.redash.io in response to customer feedback.
Closes #467
=> Updates REST SSH tunnel configuration API doc

src/pages/kb/user-guide/users/authentication-options.md
Hello,
This PR brings huge documentation improvement and clarification for SSO SAML Authentication.
PR has been established based on the opened issue https://github.com/getredash/redash/issues/2977
Kudos to @rockxsj
=> add instruction for self-hosted SAML Authentication Options

README.md, src/pages/kb/open-source/dev-guide/docker.md, src/pages/kb/open-source/dev-guide/end-to-end-tests.md, src/pages/kb/open-source/dev-guide/remote-server.md, src/pages/kb/open-source/dev-guide/setup.md
Depends on getredash/redash#5541
=> Update docs to reflect changes from getredash/redash#5541 (use Yarn instead of NPM)

src/pages/kb/open-source/admin-guide/how-to-upgrade.md, src/pages/kb/open-source/admin-guide/secrets.md, src/pages/kb/open-source/setup.md
This PR tightens the language around setting up secrets.
=> Secrets updates

src/pages/kb/open-source/dev-guide/docker.md, src/pages/kb/open-source/dev-guide/setup.md, src/pages/kb/open-source/setup.md
Fix for mentioning docs for health checkpoint API: https://github.com/getredash/redash/issues/5040
=> Add a note on health checkpoint API for redash

src/pages/kb/user-guide/users/authentication-options.md
Related to this thread on the forum: https://discuss.redash.io/t/jit-just-in-time-for-sso/9738/2
=> Add reference to JIT to help searchers

src/pages/kb/open-source/admin-guide/env-vars-settings.md, src/pages/kb/open-source/dev-guide.md, src/pages/kb/open-source/dev-guide/write-a-query-runner.md
This PR adds a new page to the dev guide that discusses how to add a new Query Runner to Redash. I started with [Arik's instructions ](https://discuss.redash.io/t/creating-a-new-query-runner-data-source-in-redash/347) from December 2016 and updated them with the latest information. Rather than Snowflake, the doc page now uses the recently added [Firebolt Query Runner](https://github.com/getredash/redash/pull/5689) as an example.
=> [New Page]: How to write a query runner

src/components/Header.jsx, src/components/SearchResults.jsx, src/data/footer_links.yml, src/pages/community/index.jsx, src/pages/contact/index.jsx, src/pages/kb/faq/eol.md, src/pages/kb/open-source/dev-guide.md, src/pages/kb/open-source/dev-guide/end-to-end-tests.md
We have decided to move our community discussions from the Discourse forum to GitHub Discussions. This is part of our effort to simplify and bring everything into one place.
We hope that this change will make it easier for everyone to participate in the community discussions and share their ideas.
As a result of this change, the Discourse forum will move into read-only mode. If anyone wants to help with creating an archive from it or importing here, please reach out.
Thank you for your understanding and we hope you find the new platform useful!
=> Update links to forum to point at github discussions.

src/pages/kb/user-guide/visualizations/formatting-axis.md
For https://github.com/getredash/redash/pull/6370
=> Document D3 number and date format strings

src/pages/kb/user-guide/visualizations/cohort-howto.md
This PR aligns the calculation with the example in the Count Satisfying Target section.
=> Fix typo in total cohort size example

.gitignore
i guess https://github.com/getredash/redash/pull/7095 applies here too
=> Add the asdf .tool-versions file to .gitignore

package.json, yarn.lock
This should resolve a few Dependabot warnings. :smile:
=> Bump Gatsby to 5.14.0

.github/workflows/restyled.yml
Same solution applied in https://github.com/getredash/redash/pull/7227
=> Use head.sha for restyled checkout

src/pages/kb/open-source/admin-guide/how-to-upgrade.md
Related ticket: https://github.com/getredash/redash/issues/7251
=> List 25.1.0 release on upgrade page

src/pages/kb/open-source/admin-guide/how-to-upgrade.md
Related ticket: https://github.com/getredash/redash/issues/7485
=> List 25.8.0 release on upgrade page
